package com.git.bean;
// Generated 2017-10-25 12:16:07 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Board generated by hbm2java
 */
public class Board implements java.io.Serializable {


     private Long id;
     private String name;
     private String description;
     private Long topicCount;
     private Long postCount;
     private Set<Topic> children = new HashSet<Topic>(0);

    public Board() {
    }

    public Board(String name, String description, Long topicCount, Long postCount, Set<Topic> children) {
       this.name = name;
       this.description = description;
       this.topicCount = topicCount;
       this.postCount = postCount;
       this.children = children;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Long getTopicCount() {
        return this.topicCount;
    }
    
    public void setTopicCount(Long topicCount) {
        this.topicCount = topicCount;
    }
    public Long getPostCount() {
        return this.postCount;
    }
    
    public void setPostCount(Long postCount) {
        this.postCount = postCount;
    }
    public Set<Topic> getChildren() {
        return this.children;
    }
    
    public void setChildren(Set<Topic> children) {
        this.children = children;
    }




}


